site_name: uv-aio-template
repo_url: https://github.com/lloyd42/uv-aio-template
site_url: https://lloyd42.github.io/uv-aio-template
site_description: This is a template repository for Python projects that use uv for their dependency management.
site_author: lloyd42
edit_uri: edit/main/docs/
repo_name: lloyd42/uv-aio-template
copyright: Maintained by <a href="https://lloyd42.com">lloyd42</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [uv_aio_template]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lloyd42/uv-aio-template
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/uv-aio-template

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
